spring:
  dubbo: 
    application:
#注册在注册中心的名称
      id: dubbo-springboot-starter-consumer
      name: dubbo-springboot-starter-consumer
#注册中心地址，zookeeper集群，启动输出可以看见链接了多个
#单zookeeper服务：
    registry: 
      address: zookeeper://127.0.0.1:2181
#暴露服务方式
    protocol:
      id: dubbo


    
